providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.build]
cmds = ["npm ci", "npm run build"]

[variables]
NODE_ENV = "production"
PORT = "8080"
HOSTNAME = "0.0.0.0"

[start]
cmd = "npm run start"
